version: "3.0"
services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
            - "/etc/letsencrypt:/etc/letsencrypt"
            - "./nginx:/etc/nginx"
  site:
    container_name: site
    hostname: site
    #build: .
    image: bbrady1992/personal-site:latest
    ports:
      - 3000:3000
  subdomain:
    container_name: subdomain
    hostname: subdomain
    build: ../subdomain-example
    image: subdomain:latest
    ports: 
      - 3000:3000
