version: "3.0"
services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
            - "/etc/letsencrypt:/etc/letsencrypt"
            - "./nginx:/etc/nginx"
  client:
    container_name: client
    hostname: client
    build: client
    image: bbrady1992/ben-brady-me-client:latest
    ports:
      - 3000:3000
  server:
    container_name: server
    hostname: server
    build: server
    image: bbrady1992/ben-brady-me-server:latest
    ports:
      - 5000:80
    volumes:
      - ./server/db:/app/db

  #subdomain:
  #  container_name: subdomain
  #  hostname: subdomain
  #  build: ../subdomain-example
  #  image: subdomain:latest
  #  ports: 
  #    - 3000:3000
