FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app

# Copy everything
COPY . ./
# Restore as distinct layers - TODO can restore step be removed?
RUN dotnet restore
ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet tool install --global dotnet-ef
#ENTRYPOINT ["/bin/sh"]
ENTRYPOINT ["dotnet", "ef", "database", "update"]
